-- Script generated for table: products
-- Generated on: Wed Dec 11 22:15:24 ICT 2024

INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 6, 6, '2024-11-17 10:20:44', 8, '2024-12-03 14:07:36', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731813687/roexdmwuolydrc8vomua.webp', 'Kẻ mắt dành cho nữ', 'K ẻ mắt metalux');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 6, 2, '2024-11-17 10:53:56', 9, '2024-12-03 17:59:27', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731815639/iehudfwy9q9sfctgcx6g.jpg', 'Son môi dành cho nữ', 'Son Luxatidute');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('false', 12, 10, '2024-11-17 11:22:08', 10, '2024-12-03 18:00:19', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731817330/davegspustuysppvreva.png', 'son dành cho nữ', 'Son môi dưỡng cao cấp');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 5, 17, '2024-11-17 11:26:36', 11, '2024-12-03 11:44:37', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731817599/x2nhktvd0cli3voilvjo.jpg', 'Phấn dành cho nữ', 'Phấn nền trát mặt');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 159, 5, '2024-11-18 22:18:46', 12, '2024-11-28 00:52:09', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731943127/kmbr9ezyexfz9zmsyem4.webp', 'Sử dụng cho da mụn hoặc da ửng đỏ. có thể dùng trực tiếp', 'Kem Lót Catrice The Corrector Anti-Redness Primer(xanh)');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 420, 6, '2024-11-18 22:29:25', 13, '2024-11-18 22:29:31', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731943766/otbhriw2x5k1tpnttfro.jpg', 'Mascara Silkygirl Lash Squad Serum Waterproof làm dày dài và cong mi 4ml - 01 Intense Black nổi bật với khả năng làm dài, dày và cong mi vượt trội. Sản phẩm ứng dụng công nghệ Pro-serum cùng đầu cọ thông minh, giúp mi dài gấp đôi, dày đến 8 lần và cong 30 độ tự nhiên.
Mascara có khả năng chống lem, chống trôi và chứa các dưỡng chất như chiết xuất hạt hoa hồng, Vitamin B5, lô hội, nuôi dưỡng mi chắc khỏe và giảm rụng mi. Với khả năng khóa giữ mi cong suốt nhiều giờ, sản phẩm còn kiểm soát dầu nhờn hiệu quả, giúp lớp trang điểm bền lâu.
Đầu cọ đặc biệt giúp tách rời từng sợi mi, tạo cảm giác tự nhiên mà không vón cục. Thành phần lành tính, phù hợp cho cả làn da nhạy cảm, mang lại làn mi dài, dày, cong quyến rũ và an toàn cho người dùng. ', 'Mascara Silkygirl Lash Squad Serum Waterproof Làm Dày Dài Và Cong Mi ');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 399, 6, '2024-11-18 22:33:47', 14, '2024-11-18 22:33:50', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944027/nvj0wjlxajpfpu5rc27v.jpg', 'Tẩy trang Mascara Milk Touch All Day Super Melting là sản phẩm chuyên dụng giúp làm sạch lớp mascara siêu bền một cách dễ dàng và hiệu quả. Với thiết kế đầu cọ dài 2 đoạn độc đáo, sản phẩm cho phép tiếp cận và làm sạch từng sợi mi từ gốc đến ngọn, mang lại trải nghiệm tẩy trang tối ưu mà không cần sử dụng bông tẩy trang. 
Công thức của sản phẩm không chứa hương liệu và chất tạo màu, đảm bảo an toàn cho da nhạy cảm và vùng da quanh mắt. Các thành phần dưỡng mi tự nhiên như dầu olive, dầu dừa, dầu thầu dầu, dầu jojoba và dầu tầm xuân giúp dưỡng ẩm, chống oxy hóa và bảo vệ làn mi khỏi các tác nhân gây hại từ môi trường. Tẩy trang Mascara Milk Touch All Day Super Melting giữ cho làn mi sạch khỏe và đẹp tự nhiên.
', 'Tẩy trang Mascara Milk Touch All Day Super Melting');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 4, 6, '2024-11-18 22:35:11', 15, '2024-12-03 11:39:29', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944113/qmqezdmqoiaubanfiyos.jpg', 'Chuốt mi 3CE Slim Fix Waterproof Mascara đến từ thương hiệu nổi tiếng 3CE có thiết kế đầu chải cong hình hạt đậu làm cho việc tạo góc cong và xử lý các khu vực khóe mi và hàng mi dưới trở nên dễ dàng hơn bao giờ hết. Kết cấu mascara chống lem trôi giúp duy trì độ cong và tạo độ dày, dài cho hàng mi một cách hiệu quả.', 'Chuốt Mi 3CE Slim Fix Waterproof Mascara');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('false', 341, 6, '2024-11-18 22:37:10', 16, '2024-12-03 20:26:30', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944232/xjp8exgeujxkyhl3dvbt.jpg', 'Mascara Loreal Paris Lash Paradise Mascara được cải tiến từ dòng mascara được nhiều thợ make up ưa chuộng - L’Oreal Paris OG Voluminous Mascara. Với thiết kế đầu chổi có dạng đồng hồ cát cùng hàng trăm sợi lông cứng, sản phẩm giúp “chiều lòng” cả những hàng lông mi mỏng và “khó nhằn” nhất. Bên cạnh đó, khả năng chống thấm nước cũng là ưu điểm khiến dòng mascara này được hội beauty blogger review nhiệt tình. ', 'Mascara Loreal Paris Lash Paradise Waterproof Mascara - 204 Black');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 181, 6, '2024-11-18 22:39:56', 17, '2024-11-18 22:40:01', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944399/zwxuqpjkvfx7ichkraut.jpg', 'Sản phẩm sử dụng công thức với lớp gel mềm và thành phần sáp giúp cố định hàng mi một cách gọn gàng mà không gây vón cục. Sản phẩm giúp làm cong mi một cách rõ ràng, chắc chắn từ gốc đến ngọn.
Phần lông cọ hình chữ C giúp phần đuôi mi lên như những chiếc móc và bám chặt vào phần đuôi mi tạo thành những lọn mi xoăn linh hoạt. Mascara có màu đen đẹp chuẩn với công thức gel lỏng trong trẻo, tạo đôi hàng mi tự nhiên, tinh tế, gọn gàng.', 'Mascara CLIO Kill Lash Superproof Mascara Dài Và Cong Mi');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 4, 6, '2024-11-18 22:42:30', 18, '2024-11-18 22:42:35', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944550/yl6rjzfbmdgch0f1hwp8.jpg', 'Mascara 3CE siêu mỏng Super Slim Waterproof là loại mascara có đầu chải siêu mảnh 2.5mm, giúp đưa mascara đến tận chân mi và chuốt mi một cách tinh tế. Sản phẩm có khả năng chống nước và chống trôi cao, giúp lông mi luôn tươi tắn và không bị lem trong thời gian dài. Chất kem mịn màng giúp tạo hiệu ứng lông mi dài, dày và uốn cong tự nhiên, giúp đôi mắt trở nên quyến rũ và cuốn hút hơn. 
Đặc biệt, mascara 3CE giúp làm sạch sợi mi, không bị vón cục và không gây kích ứng cho mắt. Sản phẩm có thiết kế siêu mỏng và nhẹ, rất dễ dàng để mang theo bên mình khi đi du lịch hoặc đi làm.', 'Mascara 3CE Siêu Mỏng Super Slim Waterproof');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 110, 6, '2024-11-18 22:44:11', 19, '2024-11-18 22:44:59', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944651/mqyukst98fpgpqfmrcr9.jpg', 'Ưu điểm lớn nhất của Mascara Focallure Làm Dài Dày Cong Mi Chống Thấm Nước Lâu Trôi 4.5g chính là khả năng chống nước, chống trôi cực tốt. Nàng có thể yên tâm tham gia các hoạt động sôi nổi mà không lo bị lem, trôi hay nhoè mascara. Hơn nữa, đầu cọ cứng cáp của sản phẩm cũng sẽ giúp nàng có được hàng mi cong vút, dày dặn và có chiều sâu hơn. 
', 'Mascara Focallure Làm Dài Dày Cong Mi Chống Thấm Nước Lâu Trôi 4.5g');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 378, 6, '2024-11-18 22:47:05', 20, '2024-11-18 22:47:08', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944826/qqoaotuf0bzexilsppqj.jpg', 'Được mệnh danh là “mascara tốt nhất châu Á”, Mascara Maybelline The Hyper Curl không để người dùng phải thất vọng khi sở hữu hàng loạt ưu điểm nổi bật như giúp làm dài mi và giúp mi cong vút bền đẹp suốt nhiều tiếng đồng hồ cùng khả năng chống nước, không lem trong nước hay môi trường ẩm. ', 'Mascara Maybelline Hyper Curl Waterproof Làm Dài, Dày Và Cong Mi mini 4.5ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 392, 6, '2024-11-18 22:49:15', 21, '2024-11-18 22:49:21', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731944956/ws8btxbko6ukjz5fzdao.jpg', 'Mascara 2 đầu Mistine, khối lượng 5g có nguồn gốc từ Thái Lan, hiện đang gây được chú ý của rất nhiều các tín đồ làm đẹp. Sản phẩm tuy nhỏ gọn nhưng lại có “võ” với cấu trúc 2 đầu chuốt. Nhờ vậy, lông mi có độ cong, dài và dày gấp nhiều lần. Đồng thời với khả năng bảo vệ làn mi chắc khỏe, không gãy rụng, đôi mắt của bạn sẽ càng cuốn hút và quyến rũ hơn.
Đặc biệt, nhờ thành phần Collagen, cùng thiết kế cọ xoắn ốc 2 mặt độc đáo, có công dụng nghiên cứu và chế tạo kỹ càng, không bị nhòe bởi mồ hôi, mỗi lần tẩy trang chỉ cần sử dụng bằng nước ấm một cách nhẹ nhàng.', 'Mascara Mistine Super Model 2 Đầu Đa Năng');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 253, 6, '2024-11-18 22:50:50', 22, '2024-11-18 22:50:53', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945051/jkouh65we3dgq9asmujv.jpg', 'Mascara Karadium On The Top Fiber đến từ thương hiệu mỹ phẩm nổi tiếng của Hàn Quốc Karadium, giúp làm dày và cong mi tự nhiên với khả năng chống trôi, chống thấm nước, đem lại điểm nhấn cho đôi mắt của bạn. Lọt top 10 sản phẩm làm đẹp Hàn Quốc được yêu thích nhất năm 2015 bên cạnh các tên tuổi lớn trong ngành mỹ phẩm, đây hứa hẹn sẽ là sản phẩm gây bão trong cộng đồng yêu làm đẹp.', 'Mascara Karadium On The Top Fiber Volume 10ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 378, 6, '2024-11-18 22:52:42', 23, '2024-11-18 22:52:48', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945163/uwaptw2jtmvm0vdmb4a3.jpg', 'Mascara Dưỡng Mi Collagen Maybelline Colossal 9.2ml được hãng ứng dụng công nghệ cao và hiện đại thể hiện ở đầu cọ đặc biệt và thành phần mascara. Sản phẩm có tác dụng làm dày mi gấp 10 lần, chứa collagen nuôi dưỡng từng sợi mi giúp bạn sở hữu một đôi mắt sắc sảo với làn mi cong cuốn hút.', 'Mascara Maybelline Colossal Waterproof Black 9.2ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 144, 6, '2024-11-18 22:54:39', 24, '2024-11-18 22:54:43', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945280/cbz0sivx3qlqeulexv7a.jpg', 'Mascara từ lâu đã là người bạn đồng hành với chị em phụ nữ với công dụng làm cong và dài mi. Không dừng lại ở đó, hãng mỹ phẩm Etude House đã nghiên cứu và cho ra đời sản phẩm Mascara chân mày Etude House Color My Brow như một sự kết hợp hoàn hảo giữa mascara và chì kẻ lông mày, giúp bạn có được một “cung ngài”bền màu, sắc nét và quyến rũ gấp 10 lần chì kẻ truyền thống.', 'Mascara mày Etude 01 Rich Brown');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 93, 6, '2024-11-18 22:56:10', 25, '2024-11-18 22:56:17', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945371/cih7aq0ux2txzqwacww9.jpg', 'Mascara Curllong J.MUE nổi bật với kích thước thon dài, nhỏ gọn. Sản phẩm có chất mực đen bóng, không vón cục, cho hàng mi lên màung J.MUE nổi bật với kích thước thon dài, nhỏ gọn. Đầu cọ mascara thông minh, siêu mảnh với đường kính chỉ 2mm giúp dễ dàng điều chỉnh, cho hàng mi cong đều, len lỏi vào từng sợi mi kể cả những sợi mi đẹp chuẩn tự nhiên.', 'Mascara J.mue Curllong Siêu Mảnh, Dài Mi');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 378, 5, '2024-11-18 22:58:34', 26, '2024-11-18 22:58:40', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945514/mlrjvzho9j8vruvvgcn2.jpg', 'Kem Lót Maybelline Fit Me Kiềm Dầu có thành phần tích hợp đất sét kiềm dầu và giữ lớp nền không bị xuống tông trong suốt 16 giờ. Chất kem dạng sữa giúp bạn tán đều dễ dàng và đem lại hiệu ứng mềm mịn cho da cũng như che phủ các khuyết điểm trên da và lỗ chân lông một cách hiệu quả. Một đặc điểm mà nhiều người yêu thích ở sản phẩm đó chính là chỉ số chống nắng SPF 20 bảo vệ làn da khỏi tác hại của tia UV.', '​​Kem Lót Maybelline Fit Me Primer Matte+Poreless SPF 20 Kiềm Dầu Ngăn Xuống Tông 30ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 231, 5, '2024-11-18 23:00:22', 27, '2024-11-18 23:00:30', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945622/lamrmlhi2eu1xfoob0il.jpg', '(Tím) hương lavender: thích hợp với làn da xanh xao, nhợt nhạt, thiếu sức sống giúp da hồng hào, tươi tắn và che đi những khuyết điểm trên da.
(Xanh lá) hương bạc hà: thích hợp cho làn da có sắc đỏ, da mụn', 'Kem Lót The Face Shop Air Cotton Makeup Base SPF30 PA++');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 420, 5, '2024-11-18 23:02:14', 28, '2024-11-18 23:02:21', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945735/d7vmey7cdxb4yrdxon12.png', 'Kem Lót SilkyGirl Instant Pore Fix Primer là một trong những sản phẩm trang điểm của hãng hiện nhận được rất nhiều sự quan tâm của khách hàng. Gây ấn tượng ngay từ phần vỏ ngoài nhỏ nhắn với màu hồng pastel nhẹ nhàng, xinh xắn, kem lót đã thực sự khiến các cô nàng có phần xao xuyến.', 'Kem Lót SilkyGirl Instant Pore Fix Primer ');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 341, 5, '2024-11-18 23:04:00', 29, '2024-11-18 23:04:06', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945840/r1tadcostfw6z1jke0tw.jpg', 'Kem Lót Loreal Infallible Kiềm Dầu Bền Màu Lâu Trôi 30ml là dòng sản phẩm hỗ trợ trang điểm rất nổi bật của L’Oreal, được nhiều makeup artist và các sao lớn ưa chuộng sử dụng. Với khả năng kiềm dầu tuyệt vời, sản phẩm giúp lớp trang điểm bền màu, xua tan nỗi lo đổ dầu, trôi makeup, giúp người dùng tự tin năng động suốt 24 tiếng đồng hồ.', 'Kem Lót Loreal Infallible Kiềm Dầu Bền Màu Lâu Trôi 30ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 110, 5, '2024-11-18 23:05:29', 30, '2024-11-18 23:05:39', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731945929/hqdx9z9ly949rpx7qtxc.jpg', 'Focallure là một thương hiệu mỹ phẩm nội địa Trung được thành lập vào năm 2020 và dần được ưa chuộng tại Việt Nam từ năm 2021. Những dòng sản phẩm của Focallure được yêu thích có thể kể đến từ son màu, phấn mắt, phấn má, kem nền… nhờ thiết kế trẻ trung, năng động, bảng thành phần an toàn và mức giá bình dân, phù hợp với nhiều đối tượng sử dụng', 'Kem Lót Focallure Glowmax Hydrating Primer Cấp Ẩm Sáng Da ');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 159, 24, '2024-11-18 23:10:15', 31, '2024-11-18 23:10:24', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731946218/tsdapbicie3biyiddqxb.jpg', '1.Kem Nền Catrice HD Liquid Coverage Foundation #10 Light Beige: dành cho tone da trắng.
2.Kem Nền Catrice HD Liquid Coverage Foundation #20 Rose Beige: dành cho tone da tự nhiên.
3.Kem Nền Catrice HD Liquid Coverage Foundation #30 Sand Beige: dành cho tone da tự nhiên, trung tính.
4.Kem Nền Catrice HD Liquid Coverage Foundation #40 Warm Beige: dành cho tone da ngăm.', 'Kem nền Catrice');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 378, 24, '2024-11-18 23:14:53', 32, '2024-11-18 23:14:59', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731946493/vtf6mqhxko6gk1ip6fgb.jpg', 'Kem Nền Maybelline Super Stay Up To 30H Lumi-Matte Foundation 110
Kem Nền Maybelline Super Stay Up To 30H Lumi-Matte Foundation 111
Kem Nền Maybelline Super Stay Up To 30H Lumi-Matte Foundation 115
Kem Nền Maybelline Super Stay Up To 30H Lumi-Matte Foundation 120', 'Kem Nền Maybelline Super Stay Up To 30H Lumi');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 181, 24, '2024-11-18 23:18:22', 33, '2024-11-18 23:18:30', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731946705/ylbfyk2ulho6h3q4qud4.webp', 'Kem nền CLIO Kill Cover Founwear Foundation SPF30 PA+++ là một sản phẩm makeup đến từ thương hiệu mỹ phẩm nổi tiếng Hàn Quốc - CLIO. Sản phẩm mang lại một lớp nền hoàn hảo, vừa có khả năng che phủ tốt các khuyết điểm, vừa chăm sóc và bảo vệ da khỏi tác hại của tia UV.', 'Kem Nền Clio');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 110, 24, '2024-11-18 23:20:09', 34, '2024-11-18 23:20:16', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731946809/e3ogz5fhkjkkfpszgvga.webp', 'Kem Nền Focallure Fluid Foundation 30g đến từ thương hiệu nội địa Trung Quốc có tên Focallure. Ngay từ khi ra mắt, sản phẩm đã nhận được sự chú ý từ các tín đồ làm đẹp với những lời khen có cánh như “kem nền có thể ngụy trang tốt những khuyết điểm và mang lại lớp nền mịn lì như nhung, bám tốt trên da suốt nhiều giờ đồng hồ”. ', 'Kem Nền Focallure ');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 139, 24, '2024-11-18 23:21:38', 35, '2024-11-18 23:21:45', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731946898/ezuo0padu4hdisuttzm2.webp', 'Kem Nền Espoir Pro Tailor Be Velvet SPF22 PA++ là dòng kem nền mới của nhà Espoir với chất kem mỏng nhẹ và mềm mịn như nhung kết hợp với công thức Comfort Velvet Formula không chỉ giúp lớp nền trở nên mềm mại mà còn ngăn chặn tình trạng khô da và bết rít', 'Kem Nền Espoir Pro Tailor Be Velvet SPF22 PA++');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 181, 25, '2024-11-18 23:23:54', 36, '2024-11-18 23:24:04', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731947036/cxqc2g5nqsmtuewtkjp7.jpg', 'Che Khuyết Điểm Clio Airy-Fit Concealer - 2BP Lingerie là sản phẩm nổi bật đến từ thương hiệu Clio, một trong những thương hiệu mỹ phẩm hàng đầu của Hàn Quốc. Sản phẩm có khối lượng 3g, thiết kế nhỏ gọn, dễ dàng mang theo bên mình. Với khả năng che phủ vượt trội, sản phẩm giúp các nàng tự tin tỏa sáng trong mọi hoàn cảnh, từ cuộc sống hàng ngày đến những bữa tiệc sang trọng.
', 'CLIO Che Khuyết Điểm Clio Airy-Fit Concealer - 2BP Lingerie');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 352, 25, '2024-11-19 00:13:14', 37, '2024-11-19 00:13:28', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731949996/nhfeiroyihhqod0pyqoj.jpg', 'Che Khuyết Điểm Lemonade Matte Addict Concealer 3g đến từ thương hiệu mỹ phẩm Việt Lemonade. Sản phẩm nổi bật với kết cấu dạng kem mỏng nhẹ, dễ tán đều nhưng vẫn có độ che phủ cao, làm mờ khuyết điểm nhanh chóng, đem đến lớp nền mịn lì không tì vết. Thêm vào đó, che khuyết điểm còn có độ bền màu cao, duy trì màu lên đến 10 tiếng, cho bạn lớp trang điểm ổn định suốt cả ngày dài.', 'Che Khuyết Điểm Lemonade');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 364, 25, '2024-11-19 00:15:40', 38, '2024-11-19 00:15:48', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731950142/u9yejcevsfwi9rutdh3p.jpg', 'Che Khuyết Điểm Luk Fixx Dành Cho Tóc Bạc Hói đến từ thương hiệu mỹ phẩm Hàn Quốc Luk. Sản phẩm nổi bật với công nghệ Lookfix có khả năng che phủ tóc hói, khu vực tóc không đều màu vô cùng tự nhiên, chỉ với một lần chạm.', 'Che Khuyết Điểm Luk Fixx Dành Cho Tóc Bạc Hói - Đen');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 234, 25, '2024-11-19 00:20:46', 39, '2024-11-19 00:20:52', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731950446/ewwffvyxrhiwb9wbgo2i.jpg', 'Kem che khuyết điểm The Saem Cover Perfection Tip Concealer SPF28/PA++ là một trong số các sản phẩm nổi tiếng nhất của thương hiệu The Saem bởi khả năng che phủ khuyết điểm, thâm, sẹo, mụn… đạt đến độ hoàn hảo. Cùng với đó là mức giá phải chăng mà ai cũng có thể sở hữu được.', 'Che Khuyết Điểm Thesame');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 378, 25, '2024-11-19 00:25:32', 40, '2024-11-19 00:25:39', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731950733/sk82u81r0mnhdujbsn6o.jpg', 'Che Khuyết Điểm Giảm Quầng Thâm Maybelline Instant Age Rewind là kem che khuyết điểm quốc dân, có khả năng che khuyết điểm vùng dưới mắt. Đặc biệt, bảng thành phần chứa Haloxyl giúp che phủ quầng thâm và bọng mắt một cách hiệu quả, tăng độ sáng bóng giúp bạn trở nên xinh đẹp và tươi trẻ hơn. Ngoài ra, nếu bạn sử dụng em nó liên tục trong thời gian dài, bạn sẽ cảm nhận được vùng thâm và bọng mắt sẽ giảm đi đáng kể.', 'Che Khuyết Điểm Maybeline');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 51, 11, '2024-11-19 00:30:29', 41, '2024-11-19 00:30:38', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731951030/zqtq44ifqyeisqjyoynw.jpg', 'Son Kem Black Rouge Icy To Fog là bộ sưu tập son mới nhất đến từ thương hiệu Black Rouge. Sản phẩm lấy cảm hứng từ sự huyền bí của thế giới phép thuật, tạo ra những màu son đầy huyền ảo, mê hoặc. ', 'Son Kem Black Rouge Icy To Fog');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 369, 10, '2024-11-19 00:34:13', 42, '2024-11-19 00:34:18', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731951253/kbif5ktrbusxa0nz6rxn.jpg', 'Son thỏi MAC đã tạo nên một cơn sốt trong giới làm đẹp với chất son lì hoàn toàn mới lạ. Thay vì lớp finish lì hoàn toàn, son MAC Powder Kiss mang đến một hiệu ứng mờ ảo, mềm mại, tạo cảm giác như đang hôn lên một đám mây.

', 'Son Thỏi MAC Powder Kiss Lipstick');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 276, 12, '2024-11-19 00:37:11', 43, '2024-11-19 00:37:15', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731951431/p7udzefe1phiq2oq3uuv.webp', 'Son Bóng Peripera là dòng son tint bóng mang đến hiệu ứng căng mọng và rạng rỡ tức thì cho đôi môi. Với công nghệ INK độc quyền, sản phẩm có chất son mỏng nhẹ, tiệp nhanh vào môi ngay từ lần chạm đầu tiên, mang lại sắc màu sống động và bền lâu suốt cả ngày. Sở hữu kết cấu nhẹ như không, Son Kem Peripera Ink Mood Glowy Tint dễ dàng lướt trên môi mà không gây cảm giác nặng hay bết dính.', 'Son Bóng Peripera');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 422, 34, '2024-11-19 00:42:25', 44, '2024-11-19 00:42:34', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731951747/dswfgodm2mt9gbjtgxwx.jpg', 'Nước Tẩy Trang Simple Water Boost Cấp Ẩm 400ml là sự lựa chọn tuyệt vời cho làn da khô và nhạy cảm. Với công thức Micellar Water chứa các hạt micelles siêu nhỏ, sản phẩm không chỉ làm sạch sâu lớp trang điểm và bụi bẩn mà còn làm dịu và cung cấp độ ẩm tức thì cho da, giúp da luôn tươi mát, mềm mại mà không gây kích ứng.', 'Nước Tẩy Trang Simple');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 296, 34, '2024-11-19 00:44:27', 45, '2024-11-19 00:44:37', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731951869/gaupoflx6jhehyz0t51u.webp', 'Nước tẩy trang Nuxe Very Rose 3 trong 1 kết hợp nước hoa hồng để loại bỏ hiệu quả lớp trang điểm, các tạp chất trên da, làm sạch da mặt và mắt. Được bổ sung phức hợp Skin-Respect Complex 100% nguồn gốc thực vật, nó làm dịu làn da từ khô đến rất khô, mang lại cảm giác thoải mái và giữ cân bằng cho da. ', 'Nước Tẩy Trang Nuxe Very Rose');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 145, 34, '2024-11-19 00:46:46', 46, '2024-11-19 00:46:54', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731952006/n2iuuqyyfir6hy6oprex.webp', 'Nước Tẩy Trang Eucerin Sensitive Skin đến từ thương hiệu mỹ phẩm nổi tiếng của Pháp Eucerin nổi bật với 3 công dung dưỡng da trong 1 sản phẩm, bao gồm: tẩy trang, rửa mặt và cân bằng da.', 'Nước Tẩy Trang Eucerin');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 119, 34, '2024-11-19 00:49:46', 47, '2024-11-19 00:49:54', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731952186/zrkmoabovuauca76fxif.webp', 'Nước Tẩy Trang Garnier là một trong những dòng sản phẩm làm sạch đình đám đến từ thương hiệu Garnier của Pháp. Với sự nghiên cứu kỹ lưỡng từng làn da, Garnier đã đem đến cho người tiêu dùng 4 phân loại nước tẩy trang có thể giải quyết vấn đề da của tất cả mọi người. 
Bằng việc ứng dụng công nghệ Micelles (Micellar Technology) với các phân tử mi-xen hoạt động theo cơ chế nam châm, sản phẩm có khả năng hút sạch nhẹ nhàng tạp chất, bụi bẩn trên da mà không hề lấy đi lớp dầu tự nhiên, không gây khô da. Bên cạnh đó, dòng tẩy trang này nhà Garnier còn đem lại công dụng cấp ẩm tuyệt vời, giúp làm mềm da, duy trì trạng thái tươi mới, trẻ trung và chống lão hoá hiệu quả.', 'Nước Tẩy Trang Garnier ');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 341, 34, '2024-11-19 00:51:52', 48, '2024-11-19 00:52:03', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731952313/ncaqu6znyij7wkmiayjt.jpg', 'Làm sạch là một bước rất quan trọng trong quá trình chăm sóc da. Một ngày da mặt phải tiếp xúc với bụi bẩn, ô nhiễm từ môi trường bên ngoài và mồ hôi, bã nhờn, tế bào da chết,... từ chính da mặt tiết ra, lâu dần, sẽ gây ra tình trạng mụn, viêm da,... Do đó, cần thiết phải có một sản phẩm giúp loại bỏ hết những tác nhân gây hại đó ra khỏi làn da của chúng ta. Nếu bạn đang tìm một sản phẩm làm sạch sâu, an toàn lại dịu nhẹ thì Nước Tẩy Trang L''Oreal Micellar Water 400ml chính là sự lựa chọn hoàn hảo.
Nước Tẩy Trang L’Oréal Micellar Water 400ml đến từ thương hiệu mỹ phẩm nổi tiếng hàng đầu thế giới L’Oréal Paris của Pháp. Đây là sản phẩm tẩy trang “quốc dân”, được nhiều người tin tưởng và sử dụng. Sản phẩm nổi bật với công nghệ Mixen đột phá theo đó, các hạt Mixen siêu nhỏ sẽ len lỏi sâu vào trong da để hút sạch các cặn trang điểm, bụi bẩn trên da mà không làm khô da hay phá hủy lớp hàng rào bảo vệ da. Nước tẩy trang  L’Oréal còn giúp cấp ẩm và cân bằng độ ẩm trên da, cho da luôn mềm mịn, căng bóng. Kết cấu dạng lỏng giúp thẩm thấu nhanh, mát da giúp da được thoải mái mà không gây bết dính. Sản phẩm chứa các thành phần lành tính, dịu nhẹ, an toàn cho da mà không gây kích ứng.', 'Nước Tẩy Trang L''Oreal');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 362, 58, '2024-11-19 00:54:04', 49, '2024-11-19 00:54:11', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731952446/tz3qoja1tj958spffsax.webp', 'Sữa Tắm Lux Botanicals Hoa Hồng Pháp Nồng Nàn 570g và Hương Phong Lan Quyến Rũ là bộ đôi sản phẩm đến từ nhà Lux. Sản phẩm có hương nước hoa cao cấp, khó cưỡng cùng nhiều dưỡng chất giúp da bạn luôn mềm mịn và lưu hương lâu.', 'Sữa Tắm Lux Botanicals Hương Hoa Thiên Điểu');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 332, 58, '2024-11-19 00:56:07', 50, '2024-11-19 00:56:13', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731952567/z8tjxf44bsibgup3zipd.webp', 'Sữa tắm là một trong những sản phẩm chăm sóc da body được nhiều người yêu thích. Sản phẩm có khả năng làm sạch, bổ sung các dưỡng chất nuôi dưỡng làn da mềm mại, khoẻ đẹp cũng như tạo hương thơm cho cơ thể.', 'Sữa Tắm Olay Hương Dâu & Bạc Hà');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 193, 58, '2024-11-19 00:58:10', 51, '2024-11-19 00:58:16', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1731952690/s7p3bxyee1509yc5apab.webp', 'Sữa Tắm Cow Bouncia Body Soap 500ml là dòng sản phẩm chăm sóc cơ thể đến từ thương hiệu Bouncia của Nhật Bản. Các sản phẩm của hãng đều được đánh giá là có chất lượng tốt, phân khúc bình dân nên nhanh chóng trở thành sự lựa chọn hàng đầu của người Nhật và khắp châu Á. 

Với thành phần chính là bơ hạt mỡ, sữa bò nguyên chất cùng hệ dưỡng ẩm chuyên sâu Hyaluronic Acid giúp dưỡng ẩm, làm sạch da, bảo vệ da khỏi những tác hại tiêu cực từ môi trường, mang đến cho bạn làn da mịn màng, tươi trẻ. Đặc biệt bơ hạt mỡ được coi là “thành phần vàng” trong việc dưỡng ẩm, có khả năng liên kết giữ nước cho da và ngậm nước. Từ đó ngăn ngừa mất nước qua lớp biểu bì và giảm tình trạng da bị kích ứng.', ' Sữa Tắm Cow Bouncia Body Soap');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 54, 83, '2024-11-26 23:25:46', 52, '2024-11-26 23:25:52', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732638348/xnhtgbwxu22fwfrjtatp.webp', 'Kem nền Bobbi Brown kiềm dầu lâu trôi 30ml là sản phẩm trang điểm cao cấp đến từ thương hiệu danh tiếng Bobbi Brown. Sản phẩm đem đến cho bạn một trải nghiệm trang điểm tối ưu với một lớp nền tự nhiên và tươi tắn.Với khả năng duy trì trên da lên đến 16 giờ, bền màu chống chuyển hóa và không gây mụn. Độ che phủ linh hoạt, từ trung bình đến full coverage, giúp che đi mọi khuyết điểm. Các hạt màu độc đáo giúp che đi những vấn đề như nếp nhăn, thâm mụn cho đến lỗ chân lông to, vùng da không đều màu và vết mẩn đỏ. Mang lại một lớp nền đa chiều khi phản chiếu ánh sáng.', 'Kem Nền Bobbi Brown');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 259, 83, '2024-11-26 23:29:10', 53, '2024-11-26 23:29:19', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732638552/mzxl4ht5mx4phasqsx2v.webp', 'Sản phẩm được đặc chế dành riêng cho làn da nhạy cảm của trẻ em, mang đến khả năng bảo vệ da trước tác hại của tia UV, đồng thời cung cấp độ ẩm cần thiết để làn da bé luôn mềm mịn, khỏe mạnh.
Sản phẩm có dạng sữa lỏng màu trắng, mùi hương nhẹ nhàng dễ chịu. Kết cấu mỏng nhẹ, thấm nhanh vào da mà không gây nhờn rít hay bết dính. Đặc biệt, sản phẩm không chứa cồn, paraben và các chất gây kích ứng, phù hợp với làn da nhạy cảm nhất.

Kissme Mommy UV Aqua Milk có chỉ số chống nắng SPF 50+ PA++++, mang lại khả năng bảo vệ toàn diện trước cả tia UVA và UVB. Sản phẩm có khả năng chống nước và mồ hôi tốt, giúp duy trì hiệu quả bảo vệ trong thời gian dài, ngay cả khi trẻ vui chơi ngoài trời hay bơi lội.', 'Sữa Chống Nắng Kissme Mommy UV Aqua Milk');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 369, 83, '2024-11-26 23:31:09', 54, '2024-11-26 23:31:16', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732638671/ltjrfgoy1up362j7rhcd.webp', 'Xịt Khoáng Khóa Lớp Trang Điểm Có Nhũ MAC Prep + Prime Face Fix + (Shimmer) 100ml là sản phẩm của thương hiệu MAC của Mỹ được ưa chuộng cực kì bởi khả năng cấp ẩm và giữ lớp trang điểm bền màu, mướt mát. Nay fan hâm mộ yêu thích của xịt khoáng Fix + giờ đây đã có thêm một sự lựa chọn mới với Fix + (Shimmer) có kết cấu thêm ánh nhũ ngọc trai cho làn da tỏa sáng. Công thức này vẫn có tất cả những công dụng của phiên bản gốc như dưỡng ẩm, làm dịu da và định hình lớp trang điểm, nhưng với phiên bản này, Xịt khoáng khoá lớp trang điểm MAC Prep + Prime Face Fix + (Shimmer) 100ml có thêm tính năng cải thiện thời gian trang điểm lâu trôi và bền màu đến 12h đồng thời bổ sung thêm tinh chất ngọc trai cho hiệu ứng làn da trông sáng khỏe, căng bóng và rạng rỡ hơn.', 'Xịt Khóa Lớp Trang Điểm MAC Có Nhũ');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 54, 83, '2024-11-26 23:34:46', 55, '2024-11-26 23:34:50', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732638888/hkapwnevzrcqhoyc41rf.jpg', 'Kem Lót Dưỡng Ẩm Bobbi Brown Vitamin Enriched Face Base 50ml là sự kết hợp đặc biệt giữa kem lót và kem dưỡng da. Không chỉ tạo lớp nền hoàn hảo cho lớp trang điểm, sản phẩm còn cung cấp các dưỡng chất cần thiết để nuôi dưỡng da, giúp da luôn mềm mịn và tươi trẻ. 

Trong Kem Lót Dưỡng Ẩm Bobbi Brown Vitamin Enriched Face Base 50ml có chứa các thành phần đặc biệt như chiết xuất Men, bơ hạt mỡ và các hợp chất vitamin B,C,E đem lại hiệu quả dưỡng ẩm cao. 

Công thức đột phá giàu dưỡng chất, cung cấp độ ẩm ngay tức thì, giúp lấp đầy các nếp nhăn và tạo nên làn da mềm mại, căng mịn, sẵn sàng cho bước trang điểm tiếp theo. Đặc biệt, sản phẩm có hương thơm dịu nhẹ của bưởi và hoa phong lữ, tạo cảm giác dễ chịu và thư giãn khi sử dụng.

Khác với các loại kem lót thông thường, Kem Lót Dưỡng Ẩm Bobbi Brown Vitamin Enriched Face Base 50ml không chứa dầu, hay hóa chất có hại, không gây cảm giác nhờn dính và làm tắc nghẽn lỗ chân lông, giúp da mặt luôn thông thoáng và khỏe mạnh.', 'Kem Lót Bobbi Brown');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 54, 83, '2024-11-26 23:36:43', 56, '2024-11-26 23:36:49', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639004/jydwh3qqkmezzutp8u8q.webp', 'Phấn Phủ Bobbi Brown Sheer Finish Pressed Powder 11g đến từ thương hiệu mỹ phẩm đình đám của Mỹ Bobbi Brown. Sản phẩm nổi bật với kết cấu dạng phấn nén với chất phấn mỏng nhẹ, thoáng khí. Khi apply lên da, phấn nhanh chóng tiệp nhanh vào da một cách tự nhiên, đem đến lớp nền trang điểm mịn màng, tinh tế.

', 'Phấn Phủ Trang Điểm Bobbi Brown');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 22, 80, '2024-11-26 23:40:27', 57, '2024-11-26 23:40:30', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639228/nsfj1muhjutlde5r9oke.webp', 'Armaf Club De Nuit EDT Intense Man là một trong những mùi hương nổi tiếng nhất của thương hiệu nước hoa Armaf. Được giới thiệu lần đầu vào năm 2015, đây là một mùi hương tinh tế và quyến rũ dành cho nam giới.

Mùi hương nước hoa thuộc hương gỗ thơm ấm áp, lịch lãm mang phong cách hiện đại, nam tính không quá nồng nàn nhưng vẫn rất quyến rũ, lôi cuốn mọi giác quan.
', 'Nước Hoa Armaf Club De Nuit Intense Man Eau De Toilette 10ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 78, 80, '2024-11-26 23:42:50', 58, '2024-11-26 23:42:54', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639372/lvqpq7dx1xs5kvxaem5k.webp', 'Nước Hoa Versace Eros EDT được ra mắt vào năm 2012 bởi nhà sáng chế nước hoa nổi tiếng Aurelien Guichard. Sản phẩm được lấy cảm hứng từ vị thần tình yêu Eros trong thần thoại Hy Lạp. Khi cho ra đời dòng nước hoa này, giám đốc điều hành của Versace, Donatella Versace chia sẻ: “Tôi đã tưởng tượng ra một người đàn ông anh hùng, đầy nhiệt huyết, gần như là một vị thần Hy Lạp. Hương thơm được tạo thành từ những nốt hương thể hiện sự gợi cảm và quyền lực, một sức mạnh tột độ của phái mạnh”.
Versace Eros EDT là một mùi hương gợi cảm, thuộc nhóm hương thơm thảo mộc, được kết hợp từ các nốt hương gỗ, phương Đông và tươi mát, tạo ra một loại nước hoa mạnh mẽ, đầy nam tính. Sản phẩm gồm 3 tầng hương thơm: mở đầu với hương thơm tươi mát, sảng khoái, không kém phần ngọt ngào từ bạc hà, tinh dầu chanh Ý và kẹo táo; hương giữa mang nét nồng nàn, dịu ngọt với hương hoa phong lữ, tinh chất cây xô thơm, hổ phách; cuối cùng là sự kết hợp đem đến sự ngọt thơm, ấm áp, quyến rũ của gỗ tuyết tùng vùng Atlas và Virginia, tinh chất cỏ Vetiver Orpur, hoắc hương Coeur Orpour, gỗ đàn hương và hương vani.
Nước Hoa Versace Eros EDT là sản phẩm có nồng độ Eau De Toilette, do đó, có khả năng lưu hương tới 10 giờ, cho phái mạnh hương thơm suốt cả ngày dài. Sản phẩm có thiết kế độc đáo, huyền bí, được lấy cảm hứng từ thần thoại Hy Lạp. Nước hoa được bao phủ bởi màu xanh dương từ biển cả. Thân chai có in hình ảnh Medusa - một nhân vật phản diện trong thần thoại Hy Lạp và cả La Mã, cùng những đường nét mê cung được bao bọc quanh thân chai, càng tôn thêm vẻ bí ẩn, thu hút. Phần nắp chai là sự kết hợp của màu xanh cùng màu vàng gold, càng tôn thêm sự quyền lực, sức thu hút của sản phẩm này. 
', 'Nước Hoa Versace Eros EDT 50ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 59, 80, '2024-11-26 23:45:29', 59, '2024-11-26 23:45:33', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639531/xe6svg4tychsphjbd4ra.jpg', 'Nước Hoa Mr.Burberry EDT là một loại nước hoa thuộc nhóm hương gỗ Woody Aromatic dành cho nam giới. Sản phẩm được tạo ra bởi nhà chế tạo nước hoa nổi tiếng Francis Kurkdjian và được ra mắt vào năm 2016.
Mr.Burberry EDT thuộc loại Eau De Toilette, mang hương thơm cổ điển nhưng không kém phần hiện đại, tinh tế và gợi cảm. Hương thơm được lấy cảm hứng từ những hương thơm tinh túy nhất của thành phố Luân Đôn xinh đẹp và những khoảnh khắc diệu kì của nó, kết hợp cùng với mùi hương cổ điển của nước Anh cùng các thành phần hương thơm độc đáo.
Nước hoa có 3 tầng hương thơm. Hương đầu là sự kết hợp đầy tươi mát của bưởi, bạch đậu khấu, ngải thơm và bạc hà. Tiếp theo, hương giữa mang hương thơm cay nồng của gỗ tuyết tùng, lá bạch dương, nhục đậu khấu và hoa oải hương. Cuối cùng, hương cuối lắng đọng với cỏ hương bài, gỗ đàn hương, gỗ Guaiac, gỗ hổ phách, nhựa bồ đề và rêu sồi.
Nước Hoa Mr.Burberry EDT có thiết kế đơn giản nhưng không kém phần nam tính, thanh lịch. Mẫu chai được lấy cảm hứng từ chiếc áo khoác Burberry màu đen mang tính biểu tượng của nhãn hàng, thể hiện chất lượng, sự khéo léo, phong cách và sức hấp dẫn vượt thời gian. Phần cổ chai có điểm nhấn độc đáo là nút thắt bằng vải gabardine dệt thủ công đầy khéo léo, tỉ mỉ, giúp tôn vinh loại vải sáng tạo được phát minh bởi Thomas Burberry - người sáng lập ra thương hiệu Burberry - hơn 100 năm trước.', 'Nước Hoa Mr.Burberry EDT 10ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 59, 80, '2024-11-26 23:45:35', 60, '2024-11-26 23:45:37', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639536/jrvlccgnmdsxxqglhcta.jpg', 'Nước Hoa Mr.Burberry EDT là một loại nước hoa thuộc nhóm hương gỗ Woody Aromatic dành cho nam giới. Sản phẩm được tạo ra bởi nhà chế tạo nước hoa nổi tiếng Francis Kurkdjian và được ra mắt vào năm 2016.
Mr.Burberry EDT thuộc loại Eau De Toilette, mang hương thơm cổ điển nhưng không kém phần hiện đại, tinh tế và gợi cảm. Hương thơm được lấy cảm hứng từ những hương thơm tinh túy nhất của thành phố Luân Đôn xinh đẹp và những khoảnh khắc diệu kì của nó, kết hợp cùng với mùi hương cổ điển của nước Anh cùng các thành phần hương thơm độc đáo.
Nước hoa có 3 tầng hương thơm. Hương đầu là sự kết hợp đầy tươi mát của bưởi, bạch đậu khấu, ngải thơm và bạc hà. Tiếp theo, hương giữa mang hương thơm cay nồng của gỗ tuyết tùng, lá bạch dương, nhục đậu khấu và hoa oải hương. Cuối cùng, hương cuối lắng đọng với cỏ hương bài, gỗ đàn hương, gỗ Guaiac, gỗ hổ phách, nhựa bồ đề và rêu sồi.
Nước Hoa Mr.Burberry EDT có thiết kế đơn giản nhưng không kém phần nam tính, thanh lịch. Mẫu chai được lấy cảm hứng từ chiếc áo khoác Burberry màu đen mang tính biểu tượng của nhãn hàng, thể hiện chất lượng, sự khéo léo, phong cách và sức hấp dẫn vượt thời gian. Phần cổ chai có điểm nhấn độc đáo là nút thắt bằng vải gabardine dệt thủ công đầy khéo léo, tỉ mỉ, giúp tôn vinh loại vải sáng tạo được phát minh bởi Thomas Burberry - người sáng lập ra thương hiệu Burberry - hơn 100 năm trước.', 'Nước Hoa Mr.Burberry EDT 10ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 153, 80, '2024-11-26 23:47:56', 61, '2024-11-26 23:47:59', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639677/l7vlpvkavnshjv3a9k3r.webp', 'Calvin Klein One EDT được chế tác thành công bởi Alberto Morillas và Harry Fremont - những nhà sáng chế nước hoa lừng danh. Sản phẩm ra mắt thị trường lần đầu tiên vào năm 1994 và được ưa chuộng đến tận ngày nay. Với phong cách tươi mát, tinh tế cùng sự trẻ trung và phóng khoáng, dòng One EDT của CK có thể phù hợp với mọi đối tượng. Dù bạn là ai, nam hay nữ, già hay trẻ, dù bạn mang màu da gì cũng đều có thể sử dụng CK One EDT. 

Ngay từ những nốt hương đầu, CK One đã khiến các giác quan như bừng tỉnh bởi hương cam, chanh, quýt và dứa hoà quyện. Tiếp theo, sự nở rộ của hương nhài tươi cùng violet, nhục đậu khấu và hoa linh lan sẽ đem lại cảm giác đắm say chưa từng có. Để rồi sự kết thúc của gỗ đàn hương cùng tuyết tùng, hổ phách, xạ hương… sẽ khiến người dùng lưu luyến mãi không quên.', 'Nước Hoa Calvin Klein One EDT 100ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 99, 80, '2024-11-26 23:52:34', 62, '2024-11-26 23:52:37', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732639955/e1vhh5iiqxdoujkwrofz.png', 'Thiết kế chai Nước hoa John Varvatos OUD For Men EDP 125ML sử dụng chất liệu chính là thuỷ tinh đúc, phần bao ngoài của chai giống như chiếc lưới được đan kết tỉ mỉ, có màu vàng đồng sang trọng và huyền bí. Đó là lý do John Varvatos OUD chính là lựa chọn hoàn hảo cho những quý ông theo đuổi phong cách sang trọng, lịch lãm và đặc biệt nam tính.', 'Nước Hoa John Varvatos OUD For Men EDP 10ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 211, 80, '2024-11-26 23:57:48', 63, '2024-11-26 23:57:54', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732640271/bykjwn8nhvdxkvr2rqiw.webp', ' Đây là thương hiệu thời trang và phong cách được thành lập vào năm 1924. Sau khi được đông đảo khách hàng biết đến và có những thành công vang dội ở lĩnh vực thời trang, hãng đã mở rộng sang cả lĩnh vực nước hoa. Hugo Boss đã cho ra đời nhiều mùi hương chất lượng dành cho nam và nữ, được các tín đồ nước hoa đón nhận nồng nhiệt. 
BST nước hoa của hãng bắt đầu với phiên bản đầu tiên là Boss Bottled Night ra ra mắt năm 2010, sau đó nhiều phiên bản tiếp theo ra đời như BOSS Bottled Sport, BOSS Bottled Unlimited, BOSS Bottled Intense, BOSS Bottled Tonic… Trong đó, nổi bật là  Boss Bottled Tonic EDT trình làng vào năm 2017 như một phiên bản nâng cấp, tươi mới hơn dành cho những quý ông hiện đại khao khát tình yêu và sự thành công. 
Hương thơm của nước hoa mang đậm tinh thần “boss”, một mùi hương đầy nam tính, mạnh mẽ và chứa đầy sinh lực. Đó là hương thơm không quá nồng nàn, sảng khoái, tươi mát với sự kết hợp của hương bưởi, cam đắng, chanh… xen lẫn chút hương cay nồng của gừng và sau đó mùi hương lắng đọng với hương gỗ đặc trưng.
Thiết kế chai nước hoa cũng khá nhẹ nhàng, đơn giản nhưng toát lên sự lạnh lùng, tinh tế. Nước hoa có màu xanh được đựng trong lọ thủy tinh trong suốt tạo nên màu sắc hấp dẫn như màu của đại dương. 
Nước hoa thuộc nồng độ EDT với phần trăm tinh chất là 15% nên hương dịu nhẹ và thoang thoảng, lưu giữ trên da lên đến 10 giờ và thích hợp dùng trong mùa thu, đông.', 'Nước hoa Hugo Boss Bottled Tonic 100ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 96, 80, '2024-11-27 00:00:06', 64, '2024-11-27 00:00:10', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732640407/edcb5wwxkxgnulxijs3c.webp', 'Từ ý tưởng đẹp như điện ảnh ấy, hai nhà điều chế nước hoa đã mở đầu sản phẩm bằng sự độc tôn của Bạch Đậu Khấu, JEAN PAUL GAULTIER Le Male Le Parfurm toát lên một nét gì đó độc đáo, táo bạo trong cách suy nghĩ và hành động khi chỉ lựa chọn duy nhất hương nước hoa cho tầng đầu tiên nhằm gây ấn tượng, lôi kéo sự thu hút, tò mò của khán giả về phía mình.

Tiếp theo, Le Male Le Parfurm lại một lần nữa chứng minh sự thông minh, lôi cuốn của mình dưới một vỏ bọc ngọt ngào nhưng không kém phần nam tính, phóng khoáng của Hoa Oải Hương và Iris để biến mình trở thành tâm điểm mỗi khi xuất hiện ở đám đông.
Cuối cùng, Le Male Le Parfurm lại khiến những người xung quanh tưởng tượng ra những cái ôm ấm áp, an toàn, đầy che chở đến từ những gã đàn ông lịch thiệp. Có lẽ, đó chính là cái ôm của sự lãng mạn của những đêm lạnh tại miền Đông nước Pháp hòa cùng hương gỗ dịu nhẹ, thoáng qua nhưng khiến ai cũng phải nhớ mãi.', 'Nước Hoa JEAN PAUL GAULTIER Le Male Le Parfurm');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 127, 80, '2024-11-27 00:03:18', 65, '2024-11-27 00:03:24', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732640603/bzqgxdq3lpykngzd7qje.jpg', 'Được ví như là “thính” của nhà Gucci, dòng nước hoa Gucci Guilty đã từng bước chinh phục và trở thành dòng nước hoa được nhiều người yêu thích, kể cả phái nam lẫn phái nữ. Năm 2020, Gucci đã tiếp tục viết tiếp câu chuyện của mình, mở ra vũ trụ #ForeverGuilty với khái niệm giải phóng tình yêu qua sự tái hiện của Nước hoa Gucci Guilty Pour Homme EDP.
Ở phiên bản lần này, các hương thơm được nâng lên một tầng cao mới, với nồng độ tinh dầu đậm đặc hơn: Eau de Parfum (EDP). Hương thơm ở phiên bản này tựa như một tuyên ngôn tình yêu phá vỡ các quy tắc và định kiến của xã hội, đem đến sự kết nối giữa những người yêu thích sự lập dị, Gucci Guilty Parfum Pour Homme là một loại nước hoa có màu hổ phách, với nhóm hương chính là hương gỗ, làm tôn lên bản chất thực sự của Gucci Guilty Pour Homme.
Gucci Guilty Pour Homme EDP mở ra với hương đầu cay nồng pha chút ngọt ngào của giấm Balsamic, ớt đỏ, muối, hoa hồng. Hương giữ đầy cuốn hút, ngọt mát, sảng khoái với hoa cam, hoa Lavender. Cuối cùng, kết thúc bằng sự ấm áp của gỗ tuyết tùng và hoắc hương. Tổng quan, nước hoa Gucci đem đến hương thơm nam tính đầy mãnh liệt, gai góc nhưng không kém phần trẻ trung, ngọt ngào, sành điệu, ga lăng.', 'Nước Hoa Gucci Guilty Pour Homme');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 183, 81, '2024-11-27 00:05:55', 66, '2024-11-27 00:06:00', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1732640757/mtvblnoeqavknzhowwvx.webp', 'Nước hoa Coach Dreams EDP được lấy cảm hứng từ những chuyến viễn du xa xôi, tại vùng đất miền Tây Hoa Kỳ đầy nắng và gió, mang theo khao khát khám phá, trải nghiệm của những người trẻ.
Thiết kế dạng chai cổ điển, thanh lịch, tạo cảm giác như một món đồ quý giá cần được trân trọng, nâng niu. Phần nắp chai thiết kế hình dáng một bông hoa trà mạ bạc, cùng điểm nhấn là chi tiết bọc da sang trọng ở cổ chai mang đặc trưng của thương hiệu Coach - nổi tiếng từ ngành làm da thủ công.', ' COACH Nước Hoa Coach Dreams EDP 60ml');
INSERT INTO products (active, brand_id, category_id, created_date, id, updated_date, thumbnail, description, name) VALUES ('true', 7, 12, '2024-12-01 21:54:00', 67, '2024-12-01 21:55:35', 'http://res.cloudinary.com/dvyx6ldqz/image/upload/v1733064842/hnrxkaobvgvpcxpd3sfc.jpg', 'mô tả sản phẩm son', 'So mikita');
