create table brands
(
    id           integer generated by default as identity
        primary key,
    active       boolean      not null,
    created_date timestamp(6),
    updated_date timestamp(6),
    name         varchar(255),
    thumbnail    varchar(500) not null
);

alter table brands
    owner to "radiant-shop_owner";

