create table categories
(
    id           integer generated by default as identity
        primary key,
    active       boolean      not null,
    created_date timestamp(6),
    updated_date timestamp(6),
    name         varchar(500) not null
        constraint ukt8o6pivur7nn124jehx7cygw5
            unique,
    parent_id    integer
        constraint fksaok720gsu4u2wrgbk10b5n8d
            references categories
);

alter table categories
    owner to "radiant-shop_owner";

create index idx_category_parent
    on categories (parent_id);

create index idx_category_name
    on categories (name);

