create table follows
(
    active      boolean      not null,
    follow_date timestamp(6) not null,
    id          bigint generated by default as identity
        primary key,
    product_id  bigint
        constraint fkdq13th3fqevpg5yexn7dhn9c7
            references products,
    user_id     bigint
        constraint fkn4am7c82j2uo8pkw4x7qibf12
            references users
);

alter table follows
    owner to "radiant-shop_owner";

