create table order_details
(
    id                bigint generated by default as identity
        primary key,
    price             bigint,
    quantity          integer not null,
    order_id          bigint
        constraint fkjyu2qbqt8gnvno9oe9j2s2ldk
            references orders,
    product_detail_id bigint
        constraint fkl9w7hjxo9qo8s0glyr4ngkm1d
            references product_details
);

alter table order_details
    owner to "radiant-shop_owner";

