create table product_reviews
(
    active       boolean not null,
    created_date timestamp(6),
    id           bigint generated by default as identity
        primary key,
    product_id   bigint
        constraint fk35kxxqe2g9r4mww80w9e3tnw9
            references products,
    reivew_date  timestamp(6),
    updated_date timestamp(6),
    email        varchar(255),
    full_name    varchar(255),
    phone_number varchar(255),
    review_text  text    not null,
    rating       integer not null
);

alter table product_reviews
    owner to "radiant-shop_owner";

