create table product_images
(
    id         bigint generated by default as identity
        primary key,
    product_id bigint
        constraint fkqnq71xsohugpqwf3c9gxmsuy
            references products,
    url        varchar(500) not null
);

alter table product_images
    owner to "radiant-shop_owner";

