create table product_details
(
    active       boolean not null,
    color_id     integer
        constraint fk5tcr8s5m0i3prlty9w0crocog
            references colors,
    discount     integer not null,
    quantity     integer not null,
    created_date timestamp(6),
    id           bigint generated by default as identity
        primary key,
    product_id   bigint
        constraint fknfvvq3meg4ha3u1bju9k4is3r
            references products,
    sale_price   bigint  not null,
    updated_date timestamp(6)
);

alter table product_details
    owner to "radiant-shop_owner";

