create table products
(
    active       boolean      not null,
    brand_id     integer
        constraint fka3a4mpsfdf4d2y6r8ra3sc8mv
            references brands,
    category_id  integer
        constraint fkog2rp4qthbtt2lfyhfo32lsw9
            references categories,
    created_date timestamp(6),
    id           bigint generated by default as identity
        primary key,
    updated_date timestamp(6),
    thumbnail    varchar(500) not null,
    description  text         not null,
    name         varchar(255) not null
);

alter table products
    owner to "radiant-shop_owner";

create index idx_product_name
    on products (name);

create index idx_product_category
    on products (category_id);

create index idx_product_brand
    on products (brand_id);

