create table user_address
(
    id            bigint generated by default as identity
        primary key,
    address       varchar(255) not null,
    email         varchar(255) not null,
    phone_number  varchar(255) not null,
    district_id   integer,
    district_name varchar(255),
    province_id   integer,
    province_name varchar(255),
    ward_code     varchar(255),
    ward_name     varchar(255),
    user_id       bigint
        constraint fkrmincuqpi8m660j1c57xj7twr
            references users,
    full_name     varchar(255)
);

alter table user_address
    owner to "radiant-shop_owner";

