create table vouchers
(
    active             boolean      not null,
    usage_limit        integer,
    created_date       timestamp(6),
    end_date           timestamp(6) not null,
    id                 bigint generated by default as identity
        primary key,
    max_discount_amout bigint,
    min_order_amout    bigint,
    start_date         timestamp(6) not null,
    updated_date       timestamp(6),
    value              bigint       not null,
    description        text,
    code               varchar(255) not null
        unique,
    type               varchar(255) not null
);

alter table vouchers
    owner to "radiant-shop_owner";

