DB_USERNAME: radiant-shop_owner
DB_PASSWORD: soMeZw2EO9bD
DB_URL : jdbc:postgresql://ep-flat-dust-a1db44dl-pooler.ap-southeast-1.aws.neon.tech/radiant-shop?user=radiant-shop_owner&password=soMeZw2EO9bD&sslmode=require
OAUTH2_FACEBOOK_CLIENT_ID: 535160425613901
OAUTH2_FACEBOOK_CLIENT_SECRET: b1b2cf6a4abe8f6d5df48cd7245025d3
OAUTH2_GOOGLE_CLIENT_ID: "417810170630-1960svakd53j9uf565vbmgu2a2vc88vr.apps.googleusercontent.com"
OAUTH2_GOOGLE_CLIENT_SECRET: "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"
MAIL_USERNAME : ngadxph30395@fpt.edu.vn
MAIL_PASSWORD : zncespnsdqqiglae
